[package]
name = "launcher"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
formats.workspace = true
game-core.workspace = true
gba-runtime.workspace = true
platform.workspace = true
extraction.workspace = true
platform-sdl3.workspace = true
game-saga.workspace = true
game-legacy.workspace = true
game-fuzors.workspace = true
anyhow = "1.0.104"

[lints]
workspace = true
