[package]
name = "game-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
platform.workspace = true
gba-runtime.workspace = true
localization.workspace = true
extraction.workspace = true
formats.workspace = true
thiserror = "2.0.20"

[lints]
workspace = true
